# Generated by Django 3.2.6 on 2021-08-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='discuss',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='forum',
        ),
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='topic',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='forum',
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.discussion'),
        ),
    ]
